version: "2"

services:
  server:
    image: usercode/imagewizard
    container_name: imagewizard
    environment:
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=info@example.com
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - General__Cache=File
      - General__Key=DEMO-KEY---PLEASE-CHANGE-THIS-KEY---PLEASE-CHANGE-THIS-KEY---PLEASE-CHANGE-THIS-KEY---==
      - FileCache__Folder=/data
      - HttpLoader__DefaultBaseUrl=https://example.com
    restart: always
    network_mode: bridge
    volumes:
      - imagewizard_data:/data