<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ImageWizard.Core\ImageWizard.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ImageWizard.Generator\ImageWizard.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
</Project>
