<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SkiaSharp" Version="4.153.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ImageWizard.Core\ImageWizard.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ImageWizard.Generator\ImageWizard.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.401" />
	  <PackageReference Update="MinVer" Version="8.0.0" />
	</ItemGroup>
</Project>
