<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="wwwroot\youtube\youtube.css" />
		<Content Remove="wwwroot\youtube\youtube.js" />
		<Content Remove="wwwroot\youtube\youtube.svg" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="wwwroot\youtube\youtube.css" />
		<EmbeddedResource Include="wwwroot\youtube\youtube.js" />
		<EmbeddedResource Include="wwwroot\youtube\youtube.svg" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ImageWizard.Utils\ImageWizard.Utils.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.401" />
	  <PackageReference Update="MinVer" Version="8.0.0" />
	</ItemGroup>	
</Project>
