<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>		
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ImageWizard.Core\ImageWizard.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs" Version="12.30.1" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.401" />
	  <PackageReference Update="MinVer" Version="8.0.0" />
	</ItemGroup>
</Project>
